In [1]:
# PyTorch可以指定用来存储和计算的设备，如使用内存的CPU或者使用显存的GPU。默认情况下，PyTorch会将数据创建在内存，然后利用CPU来计算,用torch.cuda.is_available()查看GPU是否可用:
import torch
from torch import nn
print(torch.cuda.is_available())

True


In [2]:
# 查看GPU数量：
print(torch.cuda.device_count())

2


In [3]:
#查看当前GPU索引号，索引号从0开始：
print(torch.cuda.current_device())

0


In [4]:
# 根据索引号查看GPU名字:
print(torch.cuda.get_device_name(0))

GeForce GTX 1080 Ti


In [5]:
# 默认情况下，Tensor会被存在内存上。因此，之前我们每次打印Tensor的时候看不到GPU相关标识
x = torch.Tensor([1,2,3])
print(x)
# 使用.cuda()可以将CPU上的Tensor转换（复制）到GPU上。如果有多块GPU，我们用.cuda(i)来表示第 ii 块GPU及相应的显存（ii从0开始）且cuda(0)和cuda()等价
x = x.cuda(0)
print(x)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


In [6]:
# 我们可以通过Tensor的device属性来查看该Tensor所在的设备
x.device

device(type='cuda', index=0)

In [8]:
# 我们可以直接在创建的时候就指定设备
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
print(x)
# 如果对在GPU上的数据进行运算，那么结果还是存放在GPU上
y = x**2
y

tensor([1, 2, 3], device='cuda:0')


tensor([1, 4, 9], device='cuda:0')

In [9]:
# 需要注意的是，存储在不同位置中的数据是不可以直接进行计算的。即存放在CPU上的数据不可以直接与存放在GPU上的数据进行运算，位于不同GPU上的数据也是不能直接进行计算的。
z = y + x.cpu()

RuntimeError: expected backend CUDA and dtype Long but got backend CPU and dtype Long

In [10]:
# 同Tensor类似，PyTorch模型也可以通过.cuda转换到GPU上。我们可以通过检查模型的参数的device属性来查看存放模型的设备。
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [12]:
# 可见模型在CPU上，将其转换到GPU上:
net.to(device)
list(net.parameters())[0].device

device(type='cuda', index=0)

In [16]:
# 同样的，需要保证模型输入的Tensor和模型都在同一设备上，否则会报错。
x = torch.rand(2,3).cuda()
print(net(x))

tensor([[0.0804],
        [0.1660]], device='cuda:0', grad_fn=<AddmmBackward>)
